export const FUNNEL_LEADERS_DATA = "FUNNEL_LEADERS_DATA"
export const FUNNEL_NOT_LEADERS_DATA = "FUNNEL_NOT_LEADERS_DATA"
export const HR_INFO = "HR_INFO";
export const FUNNEL_STATISTICS = "FUNNEL_STATISTICS";
export const LOGIN_FETCH_DATA = "LOGIN_FETCH_DATA";
export const OPEN_VACANCIES = "OPEN_VACANCIES";